### ISSUE TITLE
First example in documentation results in divide by 0.

### ISSUE THREAD

**Issue by adamw17** [Lienus10/yoptions#3]
If run today:

`# Chain of all FORD MOTOR COMPANY call options for next expiration date
chain = yo.get_chain_greeks(stock_ticker='F', dividend_yield=0, option_type='c', risk_free_rate=None)
print(chain.head().to_string())`

results in:

`Traceback (most recent call last):
  File "[redacted path]/option_chain.py", line 3, in <module>
    chain = yo.get_chain_greeks(stock_ticker='F', dividend_yield=0.01, option_type='c', risk_free_rate=None)
  File "[redacted path]/.local/lib/python3.10/site-packages/yoptions/main.py", line 19, in get_chain_greeks
    return __get_chain(option_type, data, dividend_yield, risk_free_rate)
  File "[redacted path]/.local/lib/python3.10/site-packages/yoptions/main.py", line 245, in __get_chain
    return __greeks(data, chain, option_type, r, dividend_yield)
  File "[redacted path]/.local/lib/python3.10/site-packages/yoptions/main.py", line 344, in __greeks
    d1 = (log(float(underlying_price) / strike[-1]) + ((r - dividend_yield) + v * v / 2.) * t) / (
ZeroDivisionError: float division by zero`

Changing to a value different than 0 like 0.1 presents the same error. None will output the frame but obviously not calculate the greeks. Not sure if PEBKAC, env or bunk data.

**Comment by Lienus10** [comment]
This problem should be solved in the latest version

**Comment by korivernon** [comment]
This has not been solved in the latest version. When I use 1 or 0, I get the greeks - when I use None, I don't get the greeks. How can I get the greeks without passing in dividend?
```
Traceback (most recent call last):
  File "/Development/Etrade/etrade-monitor/etrade_python_client/etrade_apps/yop.py", line 147, in <module>
    chain = get_friday_options_chain_for_ticker_date(ticker, call_or_put, days )
  File "/Development/Etrade/etrade-monitor/etrade_python_client/etrade_apps/yop.py", line 26, in get_friday_options_chain_for_ticker_date
    chain = yo.get_chain_greeks_date(stock_ticker=ticker, dividend_yield=1, option_type=call_or_put, expiration_date=friday_after_days_out(days, True), risk_free_rate=None)
  File "/Library/Python/3.9/lib/python/site-packages/yoptions/main.py", line 31, in get_chain_greeks_date
    return __get_chain(option_type, data, dividend_yield, risk_free_rate)
  File "/Library/Python/3.9/lib/python/site-packages/yoptions/main.py", line 249, in __get_chain
    return __greeks(data, chain, option_type, r, dividend_yield)
  File "/Library/Python/3.9/lib/python/site-packages/yoptions/main.py", line 363, in __greeks
    d1 = (log(float(underlying_price) / strike[-1]) + r * t) / (v * t_sqrt) + 0.5 * v * t_sqrt
ZeroDivisionError: float division by zero

```

**Comment by vsr2158** [comment]
Not sure if this is related but getting this as of today with the latest version of package
yo.get_chain_greeks(stock_ticker='F', dividend_yield=0, option_type='c', risk_free_rate=None) 
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/PycharmProjects/z-tastyapi/venv/lib/python3.11/site-packages/yoptions/main.py", line 19, in get_chain_greeks
    return __get_chain(option_type, data, dividend_yield, risk_free_rate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PycharmProjects/z-tastyapi/venv/lib/python3.11/site-packages/yoptions/main.py", line 245, in __get_chain
    return __greeks(data, chain, option_type, r, dividend_yield)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PycharmProjects/z-tastyapi/venv/lib/python3.11/site-packages/yoptions/main.py", line 340, in __greeks
    t_sqrt = sqrt(t)
             ^^^^^^^
ValueError: math domain error

**Comment by rafacost** [comment]
Just fixed on my PR, (https://github.com/Lienus10/yoptions/pull/9) 
Have a Good one!
